title: blog # name of the site
author: Gaëtan Jestin # name of site's author
email: ecrire@gaetan.cool # email of site's author
url: https://blog.gaetanjestin.com # root address of the site
baseurl: '' # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  Once upon a time, in a far-off land, there was a very lazy king who spent all day lounging on his throne. One day, his advisors came to him with a problem: the kingdom was running out of money.

permalink: /:slug.html

favicon: 'logo.png' # name+extension of favicon (which must be put on the root folder)
goat_counter: 'greatblog' # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  back_home_text: '/ test' # customize text for homepage link in post layout
  date_format: '%Y-%m-%d' # customize how date is formatted
  show_description: true # show blog description in home page
  lowercase_titles: true # show titles in lowercase in lists

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

future: true
